### ISSUE TITLE
[Bug]: Plugin nodes unknown in subgraphs

### ISSUE THREAD

**Issue by Swimburger** [Ironclad/rivet#114]
### What happened?

When I add AssemblyAI nodes into a subgraph, and call the subgraph from another graph, I get the following error:
```
Error: Unknown node type: assemblyAiTranscribeAudio
```

```
Error: Unknown node type: assemblyAiLemurQa
```

### What was the expected functionality?

The nodes should be known and work.

### Describe your environment

macOS using the latest Rivet release from downloads page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Swimburger** [comment]
The same error occurs when running the graph from node.js:

```
/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:786
      throw new Error(`Unknown node type: ${type}`);
            ^

Error: Unknown node type: assemblyAiTranscribeAudio
    at NodeRegistration.createDynamicImpl (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:786:13)
    at new _GraphProcessor (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:7041:53)
    at createProcessor (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:144:21)
    at runGraph (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:249:25)
    at runGraphInFile (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:132:10)

Node.js v20.5.1
```

**Comment by abrenneke** [comment]
Ah thanks for reporting, I don't think it should be that difficult of a fix.

**Comment by abrenneke** [comment]
Fixed in #118

**Comment by abrenneke** [comment]
@all-contributors please add @Swimburger for bug

**Comment by Swimburger** [comment]
Thank you for moving fast on this! This would've blocked our tutorial :)

**Comment by Swimburger** [comment]
I'm still getting the error when using it from node.js:
```
/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:788
      throw new Error(`Unknown node type: ${type}`);
            ^

Error: Unknown node type: assemblyAiTranscribeAudio
    at NodeRegistration.createDynamicImpl (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:788:13)
    at new _GraphProcessor (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-core/dist/cjs/bundle.cjs:7264:53)
    at createProcessor (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:144:21)
    at runGraph (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:249:25)
    at runGraphInFile (/Users/niels/RivetPodcastQnA/node_modules/@ironclad/rivet-node/dist/cjs/bundle.cjs:132:10)

Node.js v20.5.1
```

How are we supposed to use built-in plugins from Node.js?

**Comment by abrenneke** [comment]
That looks correct if you haven't registered the plugin on the node side - have you called `globalRivetNodeRegistry.registerPlugin(plugins.assemblyAi)`?

**Comment by Swimburger** [comment]
Splendid, that works! I was expecting something like this because in the Rivet UI you also need to enable the plugin.
I just couldn't find how to do it. Is the documented anywhere? Maybe it should be part of a sample?

**Comment by abrenneke** [comment]
// TODO 😉
